services:

  nginx1:
    image: nginx:latest
    ports:
      - 4242:80
    volumes:
      - ./Laravel1:/var/www/html
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
    links:
      - php1

  nginx2:
    image: nginx:latest
    ports:
      - 2424:80
    volumes:
      - ./Laravel2:/var/www/html
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    links:
      - php2

  php1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Laravel1:/var/www/html
    depends_on:
      - mysql

  php2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Laravel2:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_username
      MYSQL_PASSWORD: your_database_password
    ports:
      - 3306:3306